"use client";
import { dateLabel, type Course, type CourseDetails } from "../lib/academics";
import { durationLabel, goalPercent, gradeAverage, timerElapsed, type StudyData, type studyStats, type TimerKind } from "../lib/study";
import type { SavedAssignment, SavedEvent } from "../lib/workspace-codec";

export function StudyTimer({ kind, data, courses, now, onAction, onSettings }: { kind: TimerKind; data: StudyData; courses: Course[]; now: number; onAction: (action: "start" | "pause" | "resume" | "finish" | "reset", kind: TimerKind) => void; onSettings: () => void }) {
  const timer = data.active?.kind === kind ? data.active : null, blocked = !!data.active && !timer;
  const seconds = Math.max(0, Math.ceil(timer ? timer.durationSeconds - timerElapsed(timer, now) : data.timers[kind].minutes * 60));
  const name = kind === "pomodoro" ? "Pomodoro" : "Focus";
  return <div className="study-timer" aria-label={`${name} timer`}><strong className="study-clock">{String(Math.floor(seconds / 60)).padStart(2, "0")}:{String(seconds % 60).padStart(2, "0")}</strong><p>{timer?.runningSince ? "Running" : timer ? "Paused" : "Ready"} · {courses.find((c) => c.id === (timer?.courseId ?? data.timers[kind].courseId))?.code ?? "Personal"}</p><div className="study-controls"><button className="primary-button compact" disabled={blocked} onClick={() => onAction(timer ? timer.runningSince ? "pause" : "resume" : "start", kind)}>{timer ? timer.runningSince ? `Pause ${name}` : `Resume ${name}` : `Start ${name}`}</button>{timer && <><button className="secondary-button compact" onClick={() => onAction("finish", kind)}>Finish {name}</button><button className="secondary-button compact" onClick={() => { if (window.confirm("Reset this timer and discard its unrecorded study time?")) onAction("reset", kind); }}>Reset {name}</button></>}</div><p className="form-hint">{blocked ? "Finish the other timer first." : "Running timers continue while this page is closed. Finish records elapsed work; reset discards it."}</p><button className="text-button" onClick={onSettings}>Goals, timers & history</button></div>;
}

export const studyWidgetTypes = ["daily-goal", "weekly-goal", "pomodoro", "focus-timer", "task-completion", "assignment-pie", "gpa", "exams", "streak", "today"];
export default function StudyWidget({ type, data, stats, courses, assignments, events, details, today, now, system, term, onOpen, onAssignment, onEvent, onCourse, onTimer }: { type: string; data: StudyData; stats: ReturnType<typeof studyStats>; courses: Course[]; assignments: SavedAssignment[]; events: SavedEvent[]; details: Record<string, CourseDetails>; today: string; now: number; system: string; term: string; onOpen: () => void; onAssignment: (a: SavedAssignment) => void; onEvent: (e: SavedEvent) => void; onCourse: (c: Course) => void; onTimer: (action: "start" | "pause" | "resume" | "finish" | "reset", kind: TimerKind) => void }) {
  if (type === "pomodoro" || type === "focus-timer") return <StudyTimer kind={type === "pomodoro" ? "pomodoro" : "focus"} data={data} courses={courses} now={now} onAction={onTimer} onSettings={onOpen} />;
  if (type === "daily-goal" || type === "weekly-goal") {
    const daily = type === "daily-goal", seconds = daily ? stats.dailySeconds : stats.weeklySeconds, minutes = daily ? data.dailyMinutes : data.weeklyMinutes, percent = goalPercent(seconds, minutes);
    return <div className="study-goal"><div className="metric-row"><span><strong>{durationLabel(seconds)}</strong><small>{minutes ? `of ${durationLabel(minutes * 60)}` : "No target set"}</small></span><b>{minutes ? `${percent}%` : "—"}</b></div><div className="completion-track"><span style={{ width: `${percent}%` }} /></div>{!daily && <div className="week-bars">{stats.week.map((d) => <span key={d.date} title={`${dateLabel(d.date)}: ${durationLabel(d.seconds)}`}><i style={{ height: `${Math.max(0, d.seconds / Math.max(1, ...stats.week.map((v) => v.seconds)) * 100)}%` }} /><small>{dateLabel(d.date, { weekday: "short" })}</small></span>)}</div>}<p className="form-hint">Recorded sessions only; active work appears after finishing.</p><button className="text-button" onClick={onOpen}>Adjust goals / view history</button></div>;
  }
  if (type === "gpa") { const average = gradeAverage(data.grades, courses, system, term); return <div className="gpa-widget"><strong>{average ? average.value.toFixed(2) : "—"}</strong><span>{system === "Percentage" ? "Credit-weighted average (%)" : "Credit-weighted grade average"}</span><p>{term || "Unspecified term"} · {system || "Choose a GPA system in Settings"}</p><p>{average ? `${average.count} graded classes · out of ${average.max}` : "Enter grades on one matching scale. Ungraded and zero-credit classes are excluded."}</p><button className="text-button" onClick={onOpen}>Edit grades</button></div>; }
  if (type === "task-completion") { const done = assignments.filter((a) => a.status === "done").length; return <div className="completion-widget"><div className="big-number"><strong>{done}</strong><span>of {assignments.length} tasks</span></div><div className="completion-track"><span style={{ width: `${assignments.length ? done / assignments.length * 100 : 0}%` }} /></div><div className="legend-row"><span>{done} complete</span><span>{assignments.length - done} open</span></div></div>; }
  if (type === "assignment-pie") {
    const open = assignments.filter((a) => a.status !== "done"), slices = [...courses.map((c) => ({ id: c.id, label: c.code, color: c.color })), { id: "", label: "Personal", color: "#738096" }].map((c) => ({ ...c, count: open.filter((a) => a.courseId === c.id).length })).filter((c) => c.count);
    let cursor = 0; const gradient = slices.map((c) => { const from = cursor; cursor += c.count / open.length * 100; return `${c.color} ${from}% ${cursor}%`; }).join(", ");
    return <div className="pie-widget"><div className="pie-chart" style={{ background: gradient ? `conic-gradient(${gradient})` : "var(--border)" }}><span><strong>{open.length}</strong><small>open</small></span></div><div className="pie-legend">{slices.map((c) => <span key={c.id}><i style={{ background: c.color }} />{c.label}<b>{c.count}</b></span>)}{!slices.length && <p>No open assignments.</p>}</div></div>;
  }
  if (type === "exams") {
    const exams = [...assignments.filter((a) => a.type === "Exam" && a.status !== "done" && a.dateKey >= today).map((a) => ({ ...a, key: `assignment-${a.id}`, open: () => onAssignment(a) })), ...events.filter((e) => e.type === "Exam" && e.dateKey >= today).map((e) => ({ ...e, key: `event-${e.id}`, open: () => onEvent(e) }))].sort((a, b) => a.dateKey.localeCompare(b.dateKey));
    return <div className="exam-list">{exams.slice(0, 5).map((a) => <button key={a.key} onClick={a.open}><span className="exam-date"><strong>{Number(a.dateKey.slice(-2))}</strong><small>{dateLabel(a.dateKey, { month: "short" })}</small></span><span><strong>{a.title}</strong><small>{courses.find((c) => c.id === a.courseId)?.code ?? "Personal"} · {Math.round((Date.parse(a.dateKey) - Date.parse(today)) / 86400000)} days</small></span></button>)}{!exams.length && <p>No upcoming exams.</p>}</div>;
  }
  if (type === "streak") return <div className="streak-widget"><div><strong>{stats.streak} days</strong><span>Longest: {stats.longest} days</span></div><div className="streak-dots">{stats.week.map((d) => <i key={d.date} className={d.seconds > 0 ? "filled" : ""} title={`${dateLabel(d.date)}: ${durationLabel(d.seconds)}`} />)}</div><button className="text-button" onClick={onOpen}>View study history</button></div>;
  const next = assignments.find((a) => a.status !== "done");
  const agenda = [...events.filter((e) => e.dateKey === today).map((e) => ({ id: e.id, time: e.time, text: e.title, action: () => onEvent(e) })), ...courses.flatMap((c) => (details[c.id]?.meetings ?? []).filter((m) => today >= m.from && today <= m.until && m.days.includes(new Date(today + "T12:00:00Z").getUTCDay())).map((m) => ({ id: c.id + m.id, time: m.start, text: `${c.code} · ${m.location || c.room}`, action: () => onCourse(c) }))), ...assignments.filter((a) => a.dateKey === today && a.status !== "done").map((a) => ({ id: a.id, time: a.dueTime ?? "", text: `${a.title} due`, action: () => onAssignment(a) }))].sort((a, b) => a.time.localeCompare(b.time));
  return <div className="today-widget"><div className="today-column"><p className="widget-kicker">Next task</p>{next ? <><strong>{next.title}</strong><span>{dateLabel(next.dateKey)} · {next.progress}% complete</span><button className="primary-button compact" onClick={() => onAssignment(next)}>Continue work</button></> : <p>No open assignments.</p>}</div><div className="today-agenda"><p>Today’s agenda</p>{agenda.map((item) => <button className="text-button" key={item.id} onClick={item.action}>{item.time || "All day"} · {item.text}</button>)}{!agenda.length && <span>No scheduled items.</span>}</div></div>;
}
