"use client";
import { useState } from "react";
import type { Course } from "../lib/academics";
import { durationLabel, gradeSystems, segmentSeconds, type Grade, type StudyData, type TimerKind } from "../lib/study";
import { downloadDraft, useSaveProtection } from "./use-save-protection";
import { StudyTimer } from "./study-widgets";

const settingsOf = (data: StudyData) => ({ dailyMinutes: data.dailyMinutes, weeklyMinutes: data.weeklyMinutes, timers: data.timers });
const blankGrade = (system: string, term: string) => ({ id: "", courseId: "", value: "", max: system === "Percentage" ? "100" : "4", system: system || "4.0 scale", term });
export default function StudyPanel({ data, courses, system, term, studyGoal, timezone, now, onChange, onTimer, onClose }: { data: StudyData; courses: Course[]; system: string; term: string; studyGoal: string; timezone: string; now: number; onChange: (patch: Partial<StudyData>) => boolean; onTimer: (action: "start" | "pause" | "resume" | "finish" | "reset", kind: TimerKind) => void; onClose: () => void }) {
  const [settings, setSettings] = useState(() => settingsOf(data)), [savedSettings, setSavedSettings] = useState(() => settingsOf(data));
  const [grade, setGrade] = useState(() => blankGrade(system, term)), [baselineGrade, setBaselineGrade] = useState(() => blankGrade(system, term)), [error, setError] = useState("");
  const dirty = JSON.stringify(settings) !== JSON.stringify(savedSettings) || JSON.stringify(grade) !== JSON.stringify(baselineGrade);
  useSaveProtection(dirty);
  const resetGrade = () => { const blank = blankGrade(system, term); setGrade(blank); setBaselineGrade(blank); };
  const classOptions = <><option value="">Personal</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</>;
  return <div className="modal-backdrop"><section className="add-class-modal academic-editor study-panel" role="dialog" aria-modal="true" aria-label="Study and grades"><div className="modal-header"><h2>Study and grades</h2><button className="secondary-button" onClick={() => { if (!dirty || window.confirm("Discard unapplied goal and grade form edits? Download the draft first to keep a copy.")) onClose(); }}>Close study panel</button></div>
    <h3>Timers</h3><p className="form-hint">Each timer type is shared across its widget copies. One timer can be active at a time.</p><div className="study-timer-grid">{(["pomodoro", "focus"] as const).map((kind) => <StudyTimer key={kind} kind={kind} data={data} courses={courses} now={now} onAction={onTimer} onSettings={() => document.getElementById("study-goals")?.focus()} />)}</div>
    <form onSubmit={(e) => { e.preventDefault(); if (onChange(settings)) { setSavedSettings(settings); setError(""); } else setError("Goals were not accepted. Review the workspace message; your form is still here."); }}><h3 id="study-goals" tabIndex={-1}>Goals and timer settings</h3>{studyGoal && <p>Study goal: {studyGoal}</p>}<p className="form-hint">Targets use minutes. Zero means no target. Timer changes apply to the next session.</p><div className="settings-form-grid"><label>Daily target (minutes)<input type="number" min="0" max="1440" value={settings.dailyMinutes} onChange={(e) => setSettings({ ...settings, dailyMinutes: Number(e.target.value) })} /></label><label>Weekly target (minutes)<input type="number" min="0" max="10080" value={settings.weeklyMinutes} onChange={(e) => setSettings({ ...settings, weeklyMinutes: Number(e.target.value) })} /></label>{(["pomodoro", "focus"] as const).map((kind) => <fieldset key={kind}><legend>{kind === "pomodoro" ? "Pomodoro" : "Focus"}</legend><label>{kind} duration (minutes)<input type="number" min="1" max="480" value={settings.timers[kind].minutes} onChange={(e) => setSettings({ ...settings, timers: { ...settings.timers, [kind]: { ...settings.timers[kind], minutes: Number(e.target.value) } } })} /></label><label>{kind} class<select value={settings.timers[kind].courseId} onChange={(e) => setSettings({ ...settings, timers: { ...settings.timers, [kind]: { ...settings.timers[kind], courseId: e.target.value } } })}>{classOptions}</select></label></fieldset>)}</div><button className="primary-button">Save goals and timer settings</button></form>
    <h3>Study history</h3><p className="form-hint">Dates use {timezone || "your device time zone"}. Paused time is excluded. Removing history updates totals and streaks.</p><button className="secondary-button" onClick={() => downloadDraft("eduessentials-study-history.json", data.sessions)}>Download study history</button>{data.sessions.length > 0 && <button className="secondary-button" onClick={() => { if (window.confirm("Delete all recorded study history? Download a copy first to keep it. This resets calculated study totals and streaks.")) onChange({ sessions: [] }); }}>Clear study history</button>}<ul className="study-history">{[...data.sessions].sort((a, b) => b.segments.at(-1)!.end.localeCompare(a.segments.at(-1)!.end)).map((s) => <li key={s.id}><span><strong>{durationLabel(segmentSeconds(s.segments))}</strong> · {s.kind === "pomodoro" ? "Pomodoro" : "Focus"} · {courses.find((c) => c.id === s.courseId)?.code ?? "Personal"}<small>{new Date(s.segments.at(-1)!.end).toLocaleString(undefined, { timeZone: timezone || undefined })}</small></span><button className="secondary-button" aria-label={`Delete study session ${s.id}`} onClick={() => { if (window.confirm("Delete this study session? Its time will be removed from totals.")) onChange({ sessions: data.sessions.filter((item) => item.id !== s.id) }); }}>Delete session</button></li>)}</ul>{!data.sessions.length && <p>No recorded sessions yet.</p>}
    <form onSubmit={(e) => { e.preventDefault(); const value: Grade = { ...grade, id: grade.id || crypto.randomUUID(), value: Number(grade.value), max: grade.system === "4.0 scale" ? 4 : grade.system === "Percentage" ? 100 : Number(grade.max) }; if (!grade.value.trim()) { setError("Enter a grade, including zero if earned."); return; } if (onChange({ grades: [...data.grades.filter((g) => g.id !== grade.id && !(g.courseId === value.courseId && g.term === value.term && g.system === value.system)), value] })) { resetGrade(); setError(""); } else setError("Grade was not accepted. Review the workspace message; your form is still here."); }}><h3>Grades</h3><p className="form-hint">Enter your actual course grade on its original scale. The dashboard averages matching grades for “{term || "Unspecified term"}” using {system || "the GPA system chosen in Settings"}, weighted by course credits. Custom scales must share a maximum; no letter-grade conversion is assumed.</p><div className="settings-form-grid"><label>Grade class<select required value={grade.courseId} onChange={(e) => setGrade({ ...grade, courseId: e.target.value })}><option value="">Choose a class</option>{courses.map((c) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></label><label>Grade term<input maxLength={160} value={grade.term} onChange={(e) => setGrade({ ...grade, term: e.target.value })} /></label><label>Grade scale<select value={grade.system} onChange={(e) => setGrade({ ...grade, system: e.target.value, max: e.target.value === "Percentage" ? "100" : "4" })}>{gradeSystems.map((s) => <option key={s}>{s}</option>)}</select></label><label>Grade value<input required type="number" step="any" min="0" max={grade.system === "4.0 scale" ? 4 : grade.system === "Percentage" ? 100 : Number(grade.max)} value={grade.value} onChange={(e) => setGrade({ ...grade, value: e.target.value })} /></label>{grade.system === "Custom" && <label>Custom scale maximum<input required type="number" min="0.01" max="1000" step="any" value={grade.max} onChange={(e) => setGrade({ ...grade, max: e.target.value })} /></label>}</div><button className="primary-button">Save grade</button><button type="button" className="secondary-button" onClick={() => { if (JSON.stringify(grade) === JSON.stringify(baselineGrade) || window.confirm("Discard these grade form edits?")) resetGrade(); }}>Clear grade form</button></form>
    <ul className="study-history">{data.grades.map((g) => <li key={g.id}><span>{courses.find((c) => c.id === g.courseId)?.code} · {g.value} / {g.max}<small>{g.term || "Unspecified term"} · {g.system}</small></span><button className="secondary-button" onClick={() => { if (JSON.stringify(grade) !== JSON.stringify(baselineGrade) && !window.confirm("Discard the current grade form edits?")) return; const next = { ...g, value: String(g.value), max: String(g.max) }; setGrade(next); setBaselineGrade(next); }}>Edit grade</button><button className="secondary-button" onClick={() => { if (window.confirm("Delete this saved grade?")) { if (onChange({ grades: data.grades.filter((item) => item.id !== g.id) }) && grade.id === g.id) resetGrade(); } }}>Delete grade</button></li>)}</ul>{!data.grades.length && <p>No grades entered.</p>}
    {error && <p className="auth-error" role="alert">{error}</p>}<button className="secondary-button" onClick={() => downloadDraft("eduessentials-study-draft.json", { settings, grade, savedStudy: data })}>Download study draft</button>
  </section></div>;
}
